version: "2"

services:

  nginx:
    container_name: nginx
    image: nginx:1.15.7
    ports:
      - "80:80"
    volumes:
      - ./project/code:/var/www/todos
      - ./nginx/log:/var/log/nginx
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - todos

  todos:
    container_name: todos
    build: ./todos
    volumes:
      - ./project/code:/var/www/todos
    links:
      - db
    depends_on:
      - db

  db:
    container_name: db
    image: mysql:latest
    restart: always
    ports:
      - "4306:3306"
    #volumes:
     # - ./project/mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=todos
      - MYSQL_USER=todos
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    command: --default-authentication-plugin=mysql_native_password

#networks:
 # backend: